# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: badb6a2ce44488423c5e2eea38a492faa9b60b773e56174a4f0ba045b106adaf27b58382ff5f3bc803402f46716be319428be07fb89494c38c579288e89a36e5

test:
  secret_key_base: db51aa6caaaf8b90ad8d0eefefe7d9bb0ade7d7f497c821b82c1d39674e34bf551d284d23022748fd7cbb3298cdb444bcc3ea44bfea30b6b0936c00c8668623f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
